######################## default configuration ####################
baseURL = "https://akhilesh006.github.io/javaprincipal/"
title = "Java Principal"
theme = "hugo-coder"

publishDir = "docs"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "javaprincipal"
disqus_identifier = "javaprincipal"
#disqus_title
disqus_url = "https://javaprincipal.disqus.com/"

googleAnalytics = "UA-168792485-1"

[params]
  author = "Akhilesh Dhar Dubey"
  description = "Software Engineer at Irdeto | Android, Java Enthusiast | OTT"
  email = "2akhileshdubey@gmail.com"
  avatar = "https://www.gravatar.com/avatar/552d6799ed1bcf1732e15cc1909020c0.png?size=300"
  url = "https://www.linkedin.com/in/akhileshmca/"
  keywords = "java, blog, deep learning"

  info = "Software Engineer at Irdeto | Android, Java Enthusiast | OTT"
#    avatarurl = "https://www.gravatar.com/avatar/552d6799ed1bcf1732e15cc1909020c0.png?size=300"
#    gravatar = "2akhileshdubey@gmail.com"
    gravatar = "akhil.bca08@gmail.com"
    footercontent = "Those who don't remember the past are condemned to repeat it. - Dynamic Programming"

    dateformat = "January 2, 2006"

    hideFooter = false
    hideCredits = true
    hideCopyright = true
    since = 2020

    # Git Commit in Footer, uncomment the line below to enable it.
#    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "light"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
[params.fathomAnalytics]
    siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    serverURL = "analytics.example.com"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/akhilesh006"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/akhileshmca"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/akhileshmca"
[[params.social]]
    name = "StackOverflow"
    icon = "fab fa-stack-overflow"
    weight = 4
    url = "https://stackoverflow.com/users/1115406/akhilesh-dhar-dubey"
[[params.social]]
    name = "StackOverflow"
    icon = "fab fa-facebook"
    weight = 5
    url = "https://www.facebook.com/akhilesh006"

[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 3
            url = "https://github.com/onslabs"

            [[languages.en.menu.main]]
            name = "Contact me"
            weight = 5
            url = "contact/"