######################## default configuration ####################
baseURL = "https://akhilesh006.github.io/javaprincipal/"
#name = "Java Principal"
#theme = "github-style"
title = "Java Principal"
theme = "hugo-coder"

publishDir = "docs"
#copyright = "© 2019. Theme by <a href=\"https://github.com/MeiK2333/github-style\"><span>github-style</span></a>"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
#  author = "Akhilesh Dhar Dubey"
#  description = "Java Principal"
#  github = "https://github.com/akhilesh006"
#  facebook = "https://www.facebook.com/akhilesh006"
#  linkedin = "https://www.linkedin.com/in/akhileshmca"
#  twitter = "https://twitter.com/akhileshmca"
#  stackoverflow = "https://stackoverflow.com/users/1115406/akhilesh-dhar-dubey"
#  email = "2akhileshdubey@gmail.com"
#  avatar = "https://www.gravatar.com/avatar/552d6799ed1bcf1732e15cc1909020c0.png?size=300"
#  url = "https://www.linkedin.com/in/akhileshmca/"
#  keywords = "java, blog, deep learning"

    author = "Akhilesh Dhar Dubey"
    description = "Java Principal"
    keywords = "blog,developer,personal"
    info = "Software Engineer at Irdeto | Android, Java Enthusiast | OTT"
#    avatarurl = "https://www.gravatar.com/avatar/552d6799ed1bcf1732e15cc1909020c0.png?size=300"
#    gravatar = "2akhileshdubey@gmail.com"
    gravatar = "akhil.bca08@gmail.com"
    footercontent = "Those who don't remember the past are condemned to repeat it. - Dynamic Programming"

    dateformat = "January 2, 2006"

    hideFooter = false
    hideCredits = true
    hideCopyright = true
    since = 2020

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "light"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
[params.fathomAnalytics]
    siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    serverURL = "analytics.example.com"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/akhilesh006"
#[[params.social]]
#    name = "Gitlab"
#    icon = "fab fa-gitlab"
#    weight = 2
#    url = "https://gitlab.com/johndoe/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/akhileshmca"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/akhileshmca"
#[[params.social]]
#    name = "Medium"
#    icon = "fab fa-medium"
#    weight = 4
#    url = "https://medium.com/@johndoe"
#[[params.social]]
#    name = "RSS"
#    icon = "fas fa-rss"
#    weight = 5
#    url = "https://myhugosite.com/index.xml"
#    rel = "alternate"
#    type = "application/rss+xml"


[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 3
            url = "projects/"

            [[languages.en.menu.main]]
            name = "Contact me"
            weight = 5
            url = "contact/"


    [languages.pt-br]
        languagename = "Português"
        title = "João Ninguém"

        [languages.pt-br.params]
            author = "João Ninguém"
            info = "Full Stack DevOps e Mágico"
            description = "Sítio pessoal de João Ninguém"
            keywords = "blog,desenvolvedor,pessoal"
            footercontent = "Coloque algum texto aqui."

        [languages.pt-br.menu]

            [[languages.pt-br.menu.main]]
            name = "Sobre"
            weight = 1
            url = "about/"

            [[languages.pt-br.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.pt-br.menu.main]]
            name = "Projetos"
            weight = 3
            url = "projects/"

            [[languages.pt-br.menu.main]]
            name = "Contato"
            weight = 5
            url = "contact/"
